[package]
name = "kranger"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
crossterm = { version = "0.28.1", default-features = false, features = ["events"] }
phf = { version = "0.11.2", features = ["macros"] }
walkdir = "2.5.0"
